; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = xiao

[env:xiao]
framework = arduino
platform = espressif32
board = seeed_xiao_esp32s3
lib_deps =
    greiman/SdFat@^2.3.1
    ;adafruit/SdFat - Adafruit Fork @ ^2.3.103
    ;greiman/SdFs @ ^2018.6.24
debug_tool = esp-builtin
monitor_speed = 115200
upload_port = COM22
monitor_port = COM22
;build_flags =  -DARDUINO_USB_CDC_ON_BOOT=1
;monitor_dtr = 1
;monitor_rts = 1
;build_type = debug

; Remove the default standard (e.g., gnu++11)
build_unflags = -std=gnu++11
; Set to desired standard (e.g., C++17)
build_flags = -std=gnu++2a ; 'auto' keyword requires >=14


[env:sparkfun_esp32s2_thing_plus_c]
platform = espressif32
board = sparkfun_esp32s2_thing_plus_c
framework = arduino

lib_deps =
    greiman/SdFat@^2.3.1
    ;adafruit/SdFat - Adafruit Fork @ ^2.3.103
    ;greiman/SdFs @ ^2018.6.24

; Remove the default standard (e.g., gnu++11)
build_unflags = -std=gnu++11 ; arduino default is 11 but...
; Set to desired standard (e.g., C++17)
build_flags = -std=gnu++2a ; 'auto' keyword requires >=20
monitor_speed = 9600

upload_port = COM17
monitor_port = COM17



[env:feather]
platform = espressif32
board = featheresp32
framework = arduino
lib_deps =
    greiman/SdFat@^2.3.1

; Remove the default standard (e.g., gnu++11)
build_unflags = -std=gnu++11
; Set to desired standard (e.g., C++17)
build_flags = -std=gnu++2a ; 'auto' keyword requires >=14
