#include "Arduino.h"
//#include <avr/pgmspace.h>

// #define SERIAL_TX_BUFFER_SIZE 128

#include <SdFat.h>

SdFs sd;
FsFile fout;

#include <SPI.h>

#include "zmodem_config.h"
#include "zmodem_zm.h"
#include "zmodem_sz.h"
// #include "zmodem_rz.h"
//#include <SdFatUtil.h>


// SdFat asdfSD;
// FsFile myFile;
// File32 myFile;
#define SD_CS_PIN SD_SEL
// SdSpiConfig config(SD_CS_PIN, DEDICATED_SPI, SD_SCK_MHZ(16), &SPI1);



// #define TXBSIZE 1024 // tx buffer size (default 1024); must be a power of 2


#define error(s) sd.errorHalt(s)


#if defined(ARDUINO_ARCH_RP2040)
  #define SD_CONFIG SdSpiConfig(SD_SEL, DEDICATED_SPI, SD_SCK_MHZ(16), &SPI1)
#else
  #define SD_CONFIG SdSpiConfig(SD_SEL, DEDICATED_SPI, SD_SCK_MHZ(16))
#endif

// This array can be generated by tools like xxd or bin2header during the build process
constexpr unsigned char test_file[] = {
  0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x20, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x0a
};
constexpr size_t test_file_len = sizeof(test_file);


void setup() {

  
  ZSERIAL.begin(115200);
  ZSERIAL.setTimeout(TYPICAL_SERIAL_TIMEOUT);
  delay(2000);

  ZSERIAL.println("beginning");

  DSERIAL_BEGIN(9600);
  DSERIAL_SET_TIMEOUT(1200);

  ASERIAL.println(Progname);
  ASERIAL.print(F("Transfer rate: "));
  ASERIAL.println(ZMODEM_SPEED);

  ASERIAL.println(F("Regular SD Card\n"));

  // Initialize the SdCard.
  ASERIAL.println(F("About to initialize SdCard"));
  if (!sd.begin(SD_CONFIG)) {
    sd.initErrorHalt(&ASERIAL);
  }
  // depending upon your SdCard environment, SPI_HALF_SPEED may work better.
ASERIAL.println(F("About to change directory"));
  // if(!sd.chdir((const char *)("/"))) sd.errorHalt(F("sd.chdir"));
ASERIAL.println(F("SdCard setup complete"));

  // fout  = sd.open("test.txt", FILE_WRITE);
  // myFile.println("testing");
  // myFile.close();

  delay(5000);

  char cmd[14] = "flightA.csv";

  ZModemSend::zmodem_send_file(cmd);
}

void loop() {

}
